stages:
  - lint
  - build
  - deploy

image: node:14.17.0-alpine

cache:
  key:
    files:
      - package-lock.json
  paths:
    - .npm/

before_script:
  - npm ci --cache .npm --prefer-offline

eslint:
  stage: lint
  script:
    - npm run lint

prettier:
  stage: lint
  script:
    - npm run check:format

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - build
    expire_in: 1 week

deploy:
  stage: deploy
  script:
    - apk --update add openssh-client scp
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - scp -r build/* deploy@165.227.160.94:~/realworld/public
